/**
 * Central site configuration for the web app.
 * Used by metadata, sitemap, robots, and structured data so the canonical
 * origin is defined in exactly one place.
 */
export const SITE_NAME = 'GetRentos';
export const SITE_DESCRIPTION =
  'The trust-driven property operating system. One workspace for renters, landlords, owners, buyers, realtors and agents — verified identities, verified properties, escrow-secured payments.';

/** Production origin. Override with NEXT_PUBLIC_SITE_URL in non-prod environments. */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://getrentos.com').replace(
  /\/$/,
  ''
);

export const SITE_TWITTER_HANDLE = '@getrentos';

/** Default OpenGraph image (generated by app/opengraph-image.tsx at build time). */
export const SITE_OG_IMAGE = `${SITE_URL}/opengraph-image`;
